"""empty message

Revision ID: 14db0c2ccd4d
Revises: 
Create Date: 2023-03-12 12:19:09.186427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14db0c2ccd4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propertytable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('bedrooms_no', sa.Integer(), nullable=False),
    sa.Column('bathrooms_no', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('photo_filename', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('propertytable')
    # ### end Alembic commands ###
